# Generated by Django 6.0.3 on 2026-04-08 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logradouro", models.CharField(max_length=255)),
                ("numero", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "complemento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bairro", models.CharField(max_length=100)),
                ("cep", models.CharField(max_length=9)),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=2)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Familia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mae", models.CharField(blank=True, max_length=255, null=True)),
                ("pai", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "renda",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("telefone_1", models.CharField(max_length=20)),
                ("telefone_2", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("auxilio", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "nis",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Crianca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("data_nascimento", models.DateField()),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino")], max_length=2
                    ),
                ),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=14, null=True, unique=True),
                ),
                (
                    "cert_nascimento",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("data_cadastro", models.DateField(auto_now_add=True)),
                (
                    "etapa",
                    models.CharField(
                        choices=[
                            ("BERÇÁRIO", "Berçário"),
                            ("MATERNAL", "Maternal"),
                            ("PRÉ-ESCOLA", "Pré-Escola"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "endereco",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="criancas",
                        to="creches.endereco",
                    ),
                ),
                (
                    "familia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membros",
                        to="creches.familia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Unidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_unidade", models.CharField(max_length=255)),
                (
                    "endereco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades",
                        to="creches.endereco",
                    ),
                ),
            ],
        ),
    ]
