# Generated by Django 6.0.3 on 2026-04-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="familia",
            name="trabalha",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="crianca",
            name="etapa",
            field=models.CharField(
                choices=[
                    ("B1", "Berçário 1"),
                    ("B2", "Berçário 2"),
                    ("M1", "Maternal 1"),
                    ("M2", "Maternal 2"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="familia",
            name="auxilio",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
