# Generated by Django 6.0.3 on 2026-04-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creches", "0002_familia_trabalha_alter_crianca_etapa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familia",
            name="auxilio",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="familia",
            name="trabalha",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
