# Generated by Django 6.0.3 on 2026-04-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creches", "0003_alter_familia_auxilio_alter_familia_trabalha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crianca",
            name="cert_nascimento",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Certidão de Nascimento",
            ),
        ),
        migrations.AlterField(
            model_name="crianca",
            name="cpf",
            field=models.CharField(
                blank=True, max_length=14, null=True, unique=True, verbose_name="CPF"
            ),
        ),
        migrations.AlterField(
            model_name="crianca",
            name="data_cadastro",
            field=models.DateField(auto_now_add=True, verbose_name="Data de Cadastro"),
        ),
        migrations.AlterField(
            model_name="crianca",
            name="data_nascimento",
            field=models.DateField(verbose_name="Data de Nascimento"),
        ),
        migrations.AlterField(
            model_name="crianca",
            name="etapa",
            field=models.CharField(
                choices=[
                    ("B1", "Berçário 1"),
                    ("B2", "Berçário 2"),
                    ("M1", "Maternal 1"),
                    ("M2", "Maternal 2"),
                ],
                max_length=2,
                verbose_name="Etapa",
            ),
        ),
        migrations.AlterField(
            model_name="crianca",
            name="nome",
            field=models.CharField(max_length=255, verbose_name="Nome Completo"),
        ),
        migrations.AlterField(
            model_name="crianca",
            name="sexo",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Feminino")],
                max_length=2,
                verbose_name="Sexo",
            ),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="bairro",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Bairro"
            ),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="cep",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="CEP"
            ),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="cidade",
            field=models.CharField(max_length=100, verbose_name="Cidade"),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="complemento",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Complemento"
            ),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="estado",
            field=models.CharField(max_length=2, verbose_name="Estado"),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitude"),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="logradouro",
            field=models.CharField(
                max_length=255, verbose_name="Logradouro (rua, avenida, etc.)"
            ),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitude"),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="numero",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Número"
            ),
        ),
        migrations.AlterField(
            model_name="familia",
            name="auxilio",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Recebe Auxílio?"
            ),
        ),
        migrations.AlterField(
            model_name="familia",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="familia",
            name="mae",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nome da Mãe"
            ),
        ),
        migrations.AlterField(
            model_name="familia",
            name="nis",
            field=models.IntegerField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Número do NIS",
            ),
        ),
        migrations.AlterField(
            model_name="familia",
            name="pai",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nome do Pai"
            ),
        ),
        migrations.AlterField(
            model_name="familia",
            name="renda",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Renda Mensal Familiar",
            ),
        ),
        migrations.AlterField(
            model_name="familia",
            name="telefone_1",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefone 1"
            ),
        ),
        migrations.AlterField(
            model_name="familia",
            name="telefone_2",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefone 2"
            ),
        ),
        migrations.AlterField(
            model_name="familia",
            name="trabalha",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Trabalha?"
            ),
        ),
        migrations.AlterField(
            model_name="unidade",
            name="nome_unidade",
            field=models.CharField(
                max_length=255, verbose_name="Nome da Unidade de Ensino"
            ),
        ),
    ]
