# Generated by Django 6.0.3 on 2026-04-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creches", "0004_alter_crianca_cert_nascimento_alter_crianca_cpf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familia",
            name="nis",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="Número do NIS"
            ),
        ),
    ]
