# Generated by Django 6.0.3 on 2026-04-09 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creches", "0005_alter_familia_nis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crianca",
            name="cert_nascimento",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="Certidão de Nascimento",
            ),
        ),
        migrations.AlterField(
            model_name="crianca",
            name="endereco",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crianca",
                to="creches.endereco",
            ),
        ),
        migrations.AlterField(
            model_name="crianca",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome Completo"),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="bairro",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Bairro"
            ),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="cidade",
            field=models.CharField(max_length=50, verbose_name="Cidade"),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="complemento",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Complemento"
            ),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="logradouro",
            field=models.CharField(
                max_length=100, verbose_name="Logradouro (rua, avenida, etc.)"
            ),
        ),
        migrations.AlterField(
            model_name="familia",
            name="mae",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nome da Mãe"
            ),
        ),
        migrations.AlterField(
            model_name="familia",
            name="pai",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nome do Pai"
            ),
        ),
        migrations.AlterField(
            model_name="unidade",
            name="endereco",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unidade",
                to="creches.endereco",
            ),
        ),
        migrations.AlterField(
            model_name="unidade",
            name="nome_unidade",
            field=models.CharField(
                max_length=100, verbose_name="Nome da Unidade de Ensino"
            ),
        ),
    ]
