# Generated by Django 6.0.3 on 2026-04-09 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "creches",
            "0006_alter_crianca_cert_nascimento_alter_crianca_endereco_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SugestaoCreche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distancia", models.FloatField(help_text="Distância em quilômetros")),
                ("data_calculo", models.DateTimeField(auto_now=True)),
                (
                    "crianca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sugestoes",
                        to="creches.crianca",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="creches.unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sugestão de Creche",
                "ordering": ["distancia"],
            },
        ),
    ]
