# Generated by Django 6.0.3 on 2026-04-10 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creches", "0007_sugestaocreche"),
    ]

    operations = [
        migrations.CreateModel(
            name="RankingProximidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distancia_km", models.FloatField()),
                ("posicao", models.IntegerField()),
                (
                    "crianca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="creches.crianca",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="creches.unidade",
                    ),
                ),
            ],
        ),
    ]
