# Generated by Django 6.0.3 on 2026-04-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creches", "0008_rankingproximidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endereco",
            name="cep",
            field=models.CharField(
                default="00000-000", max_length=9, null=True, verbose_name="CEP"
            ),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="latitude",
            field=models.FloatField(default=0.0, null=True, verbose_name="Latitude"),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="longitude",
            field=models.FloatField(default=0.0, null=True, verbose_name="Longitude"),
        ),
    ]
