# Generated by Django 6.0.3 on 2026-04-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creches", "0009_alter_endereco_cep_alter_endereco_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endereco",
            name="cep",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="CEP"
            ),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitude"),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitude"),
        ),
    ]
