# Generated by Django 6.0.3 on 2026-04-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creches", "0010_alter_endereco_cep_alter_endereco_latitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Distrib_Vagas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ult_distrib", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
