# Generated by Django 6.0.3 on 2026-04-11 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("creches", "0011_distrib_vagas"),
    ]

    operations = [
        migrations.RenameField(
            model_name="distrib_vagas",
            old_name="ult_distrib",
            new_name="ultima_rev",
        ),
    ]
