# Generated by Django 6.0.3 on 2026-04-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creches", "0012_rename_ult_distrib_distrib_vagas_ultima_rev"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="distrib_vagas",
            options={
                "verbose_name": "Distribuição de Vaga",
                "verbose_name_plural": "Distribuição de Vagas",
            },
        ),
        migrations.AlterField(
            model_name="distrib_vagas",
            name="ultima_rev",
            field=models.DateTimeField(auto_now=True, verbose_name="Última Revisão"),
        ),
    ]
