# Generated by Django 6.0.3 on 2026-05-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creches", "0013_alter_distrib_vagas_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crianca",
            name="sexo",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Feminino")],
                max_length=1,
                verbose_name="Sexo",
            ),
        ),
    ]
